# .readthedocs.yaml
# Read the Docs configuration file
# See: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Install dependencies using Hatch
python:
  install:
    - method: pip
      path: .
      extra_requirements: []

# Build documentation using Sphinx
sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: true

# Output directory for built HTML
formats: []
